version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    groups:
      python:
        patterns: ["*"]
  - package-ecosystem: gomod
    directory: /gen/go
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
