# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: optimizer/v1/optimizer.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'optimizer/v1/optimizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ortools.sat import cp_model_pb2 as ortools_dot_sat_dot_cp__model__pb2
from ortools.sat import sat_parameters_pb2 as ortools_dot_sat_dot_sat__parameters__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1coptimizer/v1/optimizer.proto\x12\x0coptimizer.v1\x1a\x1aortools/sat/cp_model.proto\x1a ortools/sat/sat_parameters.proto\"\x80\x01\n\x0cSolveRequest\x12\x34\n\x05model\x18\x01 \x01(\x0b\x32%.operations_research.sat.CpModelProto\x12:\n\nparameters\x18\x02 \x01(\x0b\x32&.operations_research.sat.SatParameters\"J\n\rSolveResponse\x12\x39\n\x06result\x18\x01 \x01(\x0b\x32).operations_research.sat.CpSolverResponse2T\n\x10OptimizerService\x12@\n\x05Solve\x12\x1a.optimizer.v1.SolveRequest\x1a\x1b.optimizer.v1.SolveResponseBBZ@github.com/fanscore-ch/optimizer/gen/go/optimizer/v1;optimizerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'optimizer.v1.optimizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z@github.com/fanscore-ch/optimizer/gen/go/optimizer/v1;optimizerv1'
  _globals['_SOLVEREQUEST']._serialized_start=109
  _globals['_SOLVEREQUEST']._serialized_end=237
  _globals['_SOLVERESPONSE']._serialized_start=239
  _globals['_SOLVERESPONSE']._serialized_end=313
  _globals['_OPTIMIZERSERVICE']._serialized_start=315
  _globals['_OPTIMIZERSERVICE']._serialized_end=399
# @@protoc_insertion_point(module_scope)
