# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from optimizer.v1 import optimizer_pb2 as optimizer_dot_v1_dot_optimizer__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in optimizer/v1/optimizer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OptimizerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Solve = channel.unary_unary(
                '/optimizer.v1.OptimizerService/Solve',
                request_serializer=optimizer_dot_v1_dot_optimizer__pb2.SolveRequest.SerializeToString,
                response_deserializer=optimizer_dot_v1_dot_optimizer__pb2.SolveResponse.FromString,
                _registered_method=True)


class OptimizerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Solve(self, request, context):
        """Solves a caller-defined model. No application data is loaded or persisted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OptimizerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Solve': grpc.unary_unary_rpc_method_handler(
                    servicer.Solve,
                    request_deserializer=optimizer_dot_v1_dot_optimizer__pb2.SolveRequest.FromString,
                    response_serializer=optimizer_dot_v1_dot_optimizer__pb2.SolveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'optimizer.v1.OptimizerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('optimizer.v1.OptimizerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OptimizerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Solve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/optimizer.v1.OptimizerService/Solve',
            optimizer_dot_v1_dot_optimizer__pb2.SolveRequest.SerializeToString,
            optimizer_dot_v1_dot_optimizer__pb2.SolveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
